// Aici adaugi noile cuvinte sub forma: { c: "varianta_corectă", w: "varianta_greșită" }
const probWordsDB = [
  { c: "mostră", w: "monstră" },
  { c: "repercusiune", w: "repercursiune" },
  { c: "excavator", w: "escavator" },
  { c: "genuflexiune", w: "genoflexiune" },
  { c: "bleumarin", w: "bleu-marin" },
  { c: "proprietar", w: "propietar" },
  { c: "itinerar", w: "itinerariu" },
  { c: "astă-seară", w: "astă seară" },
  { c: "așază", w: "așează" },
  { c: "voiam", w: "vroiam" },
  { c: "chibrituri", w: "chibrite" },
  { c: "aragaze", w: "aragazuri" },
  { c: "bareme", w: "baremuri" },
  { c: "succese", w: "succesuri" },
  { c: "monede", w: "monezi" },
  { c: "boschete", w: "boscheți" },
  { c: "colonei", w: "coloneli" },
  { c: "pancarte", w: "pancărți" },
  { c: "sindroame", w: "sindromuri" },
  { c: "sloganuri", w: "slogane" },
  { c: "morminte", w: "mormânturi" },
  { c: "snoabe", w: "snobe" },
  { c: "parbrize", w: "parbrizuri" },
  { c: "bairamuri", w: "bairame" },
  { c: "niveluri (stadii)", w: "nivele (stadii)" },
  { c: "refrene", w: "refrenuri" },
  { c: "feșe", w: "fașe" },
  { c: "vopsele", w: "vopseluri" },
  { c: "marmuri", w: "marmure" },
  { c: "înșală", w: "înșeală" },
  { c: "creează", w: "crează" },
  { c: "înnoadă", w: "înoadă" },
  { c: "înot", w: "înnot" },
  { c: "deseară (diseară)", w: "de seară (diseară)" },
  { c: "nicidecum", w: "nici de cum" },
  { c: "niciun (adjectiv)", w: "nici un (adjectiv)" },
  { c: "odată (cândva)", w: "o dată (cândva)" },
  { c: "altădată", w: "altă dată (în trecut)" },
  { c: "nu fi", w: "nu fii" },
  { c: "fii", w: "fi (tu)" },
  { c: "știi", w: "ști" },
  { c: "ți-ar", w: "țiar" },
  { c: "să aibă", w: "să aibe" },
  { c: "să țină", w: "să ție" },
  { c: "să vină", w: "să vie" },
  { c: "să dea", w: "să deie" },
  { c: "din cauza (de rău)", w: "datorită (de rău)" },
  { c: "respectuos", w: "respectos" },
  { c: "astmatic", w: "asmatic" },
  { c: "greșeală", w: "greșală" },
  { c: "înșelăciune", w: "înșealăciune" },
  { c: "delincvent", w: "delicvent" },
  { c: "panglică", w: "pamblică" },
  { c: "frustrare", w: "frustare" },
  { c: "abțibild", w: "abțiguib" },
  { c: "sandviș", w: "sanviș" },
  { c: "șnițel", w: "șnițel (cu s)" }, 
  { c: "mândri", w: "mândrii (nearticulat)" },
  { c: "copiii", w: "copii (articulat)" },
  { c: "miniștrii", w: "miniștri (articulat)" },
  { c: "bărbații", w: "bărbați (articulat)" },
  { c: "pe care (acuzativ)", w: "care (acuzativ)" },
  { c: "salariu", w: "salar" },
  { c: "serviciu", w: "servici" },
  { c: "albaștri", w: "albaștrii (nearticulat)" },
  { c: "v-ați", w: "va-ți" },
  { c: "s-au (verb)", w: "sau (verb)" },
  { c: "printr-un", w: "printrun" },
  { c: "dintr-o", w: "dintro" },
  { c: "aceeași (f.)", w: "aceiași (f.)" },
  { c: "așadar", w: "așa dar" },
  { c: "deodată", w: "de o dată" },
  { c: "totodată", w: "tot o dată" },
  { c: "vreun", w: "vre-un" },
  { c: "nicio", w: "nici-o" },
  { c: "dedesubt", w: "dedesupt" },
  { c: "prerie", w: "preerie" },
  { c: "clovn", w: "claun" },
  { c: "dezamăgi", w: "dezămăgi" },
  { c: "țigară", w: "țigare" },
  { c: "cireașă", w: "cireșe (la singular)" },
  { c: "gogoașă", w: "gogoșe (la singular)" },
  { c: "bancnotă", w: "bacnotă" },
  { c: "piuneză", w: "pioneză" },
  { c: "chiuvetă", w: "ghiuvetă" },
  { c: "marșarier", w: "marșalier" },
  { c: "complee", w: "compleuri" },
  { c: "reper", w: "reper (accent greșit)" },
  { c: "șasiu", w: "șasiu (accent greșit)" },
  { c: "mijloc", w: "miljoc" },
  { c: "pieri", w: "pierii" },
  { c: "vadră", w: "vadră (accent)" },
  { c: "făraș", w: "făraș (accent)" },
  { c: "ouă", w: "ouăle" },
  { c: "chibrit", w: "chibrite" },
  { c: "roșcove", w: "roșcove" }
];
