// Aici adaugi noile cuvinte sub forma: { c: "varianta_corectă", w: "varianta_greșită" }
const probWordsDB = [
  { c: "mostră", w: "monstră" },
  { c: "repercusiune", w: "repercursiune" },
  { c: "excavator", w: "escavator" },
  { c: "genuflexiune", w: "genoflexiune" },
  { c: "bleumarin", w: "bleu-marin" },
  { c: "proprietar", w: "propietar" },
  { c: "itinerar", w: "itinerariu" },
  { c: "astă-seară", w: "astă seară" },
  { c: "așază", w: "așează" },
  { c: "voiam", w: "vroiam" },
  { c: "chibrituri", w: "chibrite" },
  { c: "aragaze", w: "aragazuri" },
  { c: "bareme", w: "baremuri" },
  { c: "succese", w: "succesuri" },
  { c: "monede", w: "monezi" },
  { c: "boschete", w: "boscheți" },
  { c: "colonei", w: "coloneli" },
  { c: "pancarte", w: "pancărți" },
  { c: "morminte", w: "mormânturi" },
  { c: "snoabe", w: "snobe" },
  { c: "parbrize", w: "parbrizuri" },
  { c: "bairamuri", w: "bairame" },
  { c: "niveluri (stadii)", w: "nivele (stadii)" },
  { c: "refrene", w: "refrenuri" },
  { c: "feșe", w: "fașe" },
  { c: "vopsele", w: "vopseluri" },
  { c: "marmuri", w: "marmure" },
  { c: "înșală", w: "înșeală" },
  { c: "creează", w: "crează" },
  { c: "înnoadă", w: "înoadă" },
  { c: "înot", w: "înnot" },
  { c: "deseară (diseară)", w: "de seară (diseară)" },
  { c: "nicidecum", w: "nici de cum" },
  { c: "niciun (adjectiv)", w: "nici un (adjectiv)" },
  { c: "odată (cândva)", w: "o dată (cândva)" },
  { c: "altădată", w: "altă dată (în trecut)" },
  { c: "nu fi", w: "nu fii" },
  { c: "fii", w: "fi (tu)" },
  { c: "știi", w: "ști" },
  { c: "ți-ar", w: "țiar" },
  { c: "să aibă", w: "să aibe" },
  { c: "să țină", w: "să ție" },
  { c: "să vină", w: "să vie" },
  { c: "să dea", w: "să deie" },
  { c: "din cauza (de rău)", w: "datorită (de rău)" },
  { c: "respectuos", w: "respectos" },
  { c: "astmatic", w: "asmatic" },
  { c: "greșeală", w: "greșală" },
  { c: "înșelăciune", w: "înșealăciune" },
  { c: "delincvent", w: "delicvent" },
  { c: "panglică", w: "pamblică" },
  { c: "frustrare", w: "frustare" },
  { c: "abțibild", w: "acțibild" },
  { c: "sandviș", w: "sanviș" },
  { c: "șnițel", w: "snițel" }, 
  { c: "mândri", w: "mândrii (nearticulat)" },
  { c: "copiii", w: "copii (articulat)" },
  { c: "miniștrii", w: "miniștri (articulat)" },
  { c: "bărbații", w: "bărbați (articulat)" },
  { c: "pe care (acuzativ)", w: "care (acuzativ)" },
  { c: "salariu", w: "salar" },
  { c: "serviciu", w: "servici" },
  { c: "albaștri", w: "albaștrii (nearticulat)" },
  { c: "v-ați", w: "va-ți" },
  { c: "s-au (verb)", w: "sau (verb)" },
  { c: "printr-un", w: "printrun" },
  { c: "dintr-o", w: "dintro" },
  { c: "aceeași (f.)", w: "aceiași (f.)" },
  { c: "așadar", w: "așa dar" },
  { c: "deodată", w: "de o dată" },
  { c: "totodată", w: "tot o dată" },
  { c: "vreun", w: "vre-un" },
  { c: "nicio", w: "nici-o" },
  { c: "dedesubt", w: "dedesupt" },
  { c: "prerie", w: "preerie" },
  { c: "clovn", w: "claun" },
  { c: "dezamăgi", w: "dezămăgi" },
  { c: "țigară", w: "țigare" },
  { c: "cireașă", w: "cireșe (la singular)" },
  { c: "gogoașă", w: "gogoșe (la singular)" },
  { c: "bancnotă", w: "bacnotă" },
  { c: "piuneză", w: "pioneză" },
  { c: "chiuvetă", w: "ghiuvetă" },
  { c: "marșarier", w: "marșalier" },
  { c: "compleuri", w: "complee" },
  { c: "mijloc", w: "miljoc" },
  { c: "ouă", w: "ouo" },
  { c: "roșcove", w: "roșcoave" },
  { c: "pancartă", w: "pancardă" },
  { c: "tobogan", w: "topogan" },
  { c: "rucsac", w: "ruczac" },
  { c: "vise (imagini în somn)", w: "visuri (imagini în somn)" },
  { c: "visuri (idealuri)", w: "vise (idealuri)" },
  { c: "va veni", w: "v-a veni" },
  { c: "ați", w: "a-ți (când e verb auxiliar)" },

  { c: "Eu am o mostră de parfum.", w: "Eu am o monstră de parfum." },
  { c: "Acesta are repercusiuni grave.", w: "Acesta are repercursiuni grave." },
  { c: "Muncitorul conduce un excavator.", w: "Muncitorul conduce un escavator." },
  { c: "Am făcut zece genuflexiuni.", w: "Am făcut zece genoflexiuni." },
  { c: "Mi-am cumpărat un tricou bleumarin.", w: "Mi-am cumpărat un tricou bleu-marin." },
  { c: "El este proprietarul casei.", w: "El este propietarul casei." },
  { c: "Am stabilit un itinerar clar.", w: "Am stabilit un itinerariu clar." },
  { c: "Vii la mine astă-seară?", w: "Vii la mine astă seară?" },
  { c: "Băiatul așază paharul pe masă.", w: "Băiatul așează paharul pe masă." },
  { c: "Voiam să merg la film.", w: "Vroiam să merg la film." },
  { c: "Am cumpărat două aragaze.", w: "Am cumpărat două aragazuri." },
  { c: "Nu au atins aceste bareme.", w: "Nu au atins aceste baremuri." },
  { c: "Am obținut numeroase succese.", w: "Am obținut numeroase succesuri." },
  { c: "Am găsit trei monede vechi.", w: "Am găsit trei monezi vechi." },
  { c: "S-a ascuns după boschete.", w: "S-a ascuns după boscheți." },
  { c: "Pe stradă sunt multe pancarte.", w: "Pe stradă sunt multe pancărți." },
  { c: "Zidarii au adus noi vopsele.", w: "Zidarii au adus noi vopseluri." },
  { c: "Fata se înșală amarnic.", w: "Fata se înșeală amarnic." },
  { c: "Ea creează rochii de seară.", w: "Ea crează rochii de seară." },
  { c: "Băiatul înnoadă șireturile.", w: "Băiatul înoadă șireturile." },
  { c: "Băiatul merge la cursuri de înot.", w: "Băiatul merge la cursuri de înnot." },
  { c: "Ne vedem deseară în parc.", w: "Ne vedem de seară în parc." },
  { c: "Nu a fost nicidecum vina ei.", w: "Nu a fost nici de cum vina ei." },
  { c: "Niciun om nu a venit.", w: "Nici un om nu a venit." },
  { c: "A fost odată un prinț.", w: "A fost o dată un prinț." },
  { c: "Ne vom întâlni altădată.", w: "Ne vom întâlni altă dată." },
  { c: "Te rog să nu fii supărat.", w: "Te rog să nu fi supărat." },
  { c: "Nu fi obraznic!", w: "Nu fii obraznic!" },
  { c: "Fii cuminte la școală!", w: "Fi cuminte la școală!" },
  { c: "Tu știi lecția la istorie?", w: "Tu ști lecția la istorie?" },
  { c: "Ți-ar plăcea o înghețată?", w: "Țiar plăcea o înghețată?" },
  { c: "Sper să aibă noroc.", w: "Sper să aibe noroc." },
  { c: "Sper să vină mai repede.", w: "Sper să vie mai repede." },
  { c: "A refuzat să dea înapoi.", w: "A refuzat să deie înapoi." },
  { c: "Băiatul este foarte respectuos.", w: "Băiatul este foarte respectos." },
  { c: "Ai făcut o greșeală mare.", w: "Ai făcut o greșală mare." },
  { c: "Poliția a prins acel delincvent.", w: "Poliția a prins acel delicvent." },
  { c: "Fetița are o panglică roșie.", w: "Fetița are o pamblică roșie." },
  { c: "Am un abțibild cu o mașină.", w: "Am un acțibild cu o mașină." },
  { c: "Am mâncat un sandviș cu șuncă.", w: "Am mâncat un sanviș cu șuncă." },
  { c: "Azi la prânz avem șnițel.", w: "Azi la prânz avem snițel." },
  { c: "Copiii au plecat la joacă.", w: "Copii au plecat la joacă." },
  { c: "Aceștia sunt miniștrii țării.", w: "Aceștia sunt miniștri țării." },
  { c: "Cartea pe care o citesc este lungă.", w: "Cartea care o citesc este lungă." },
  { c: "Bunicul a primit un salariu mare.", w: "Bunicul a primit un salar mare." },
  { c: "El se duce zilnic la serviciu.", w: "El se duce zilnic la servici." },
  { c: "Ochii ei sunt albaștri.", w: "Ochii ei sunt albaștrii." },
  { c: "Băieții s-au dus la munte.", w: "Băieții sau dus la munte." },
  { c: "A intrat dintr-odată pe ușă.", w: "A intrat dintr-o dată pe ușă." },
  { c: "Pisica se ascunde dedesubt.", w: "Pisica se ascunde dedesupt." }

  { c: "Afară s-a înnorat puternic.", w: "Afară s-a înorat puternic." },
  { c: "A început să se înnopteze.", w: "A început să se înopteze." },
  { c: "Hainele s-au înnegrit de fum.", w: "Hainele s-au înegrit de fum." },
  { c: "Vrea să-și înnoiască garderoba.", w: "Vrea să-și înoiască garderoba." },
  { c: "Nu vreau să te înnebunesc cu asta.", w: "Nu vreau să te înebunesc cu asta." },
  { c: "Gestul lui l-a înnobilat.", w: "Gestul lui l-a înobilat." },
  { c: "Mașina s-a înnămolit pe drum.", w: "Mașina s-a înămolit pe drum." },
  { c: "Cerul este tare înnegurat azi.", w: "Cerul este tare înegurat azi." },
  { c: "El are un talent înnăscut la desen.", w: "El are un talent înăscut la desen." },
  { c: "Peștele înoată foarte rapid.", w: "Peștele înnoată foarte rapid." },
  { c: "Competiția de înot a fost grea.", w: "Competiția de înnot a fost grea." }
];
